Update `context.js` and `constants.js`
digitalbazaar/vc-status-list-context pull request #1
Opened 2022-01-27 14:03 UTC by JSAssassin

2022-01-27 22:53 UTC, msporny approved these changes

2022-01-28 01:18 UTC, davidlehn approved these changes

2022-01-28 15:09 UTC, dlongley requested changes

2022-01-28 15:09 UTC, dlongley commented on js/context.js
> +          'https://w3id.org/vc/status-list#statusListCredential'
```suggestion
          'https://w3id.org/vc/status-list#statusListIndex'
```

2022-01-28 15:12 UTC, dlongley commented on js/context.js
> +          'https://w3id.org/vc/status-list#statusListCredential'
This appears to be correct over here: https://github.com/w3c-ccg/vc-status-list-2021/blob/main/contexts/v1.jsonld#L66

I recommend doing a diff to make sure human eyes didn't miss anything else.

2022-01-28 15:14 UTC, JSAssassin commented on js/context.js
> +          'https://w3id.org/vc/status-list#statusListCredential'
Thank you for catching that, will do.

2022-01-28 15:24 UTC, JSAssassin commented on js/context.js
> +          'https://w3id.org/vc/status-list#statusListCredential'
Fixed here 2f51823

2022-01-28 15:36 UTC, dlongley approved these changes

2022-01-28 20:41 UTC, dmitrizagidulin approved these changes
:+1: 
Thanks @JSAssassin!

2022-01-28 20:55 UTC, davidlehn commented
Re syncing js and json issues: I think the theory of this newer template style is that developers should just edit the js and use the `serialize` script to generate and commit the JSON.  @dmitrizagidulin should confirm.  I assume the generated JSON is supposed to be in git?  The `build` script is going to run `serialize` anyway so I think the main purpose for the JSON in the repo is for local testing?

2022-01-28 20:59 UTC, dmitrizagidulin commented
@davidlehn - good question. Yes, the generated JSON is supposed to be committed to Git. The reason for that is -- for many of the contexts this template serves, the w3id URL resolves to that very same generated JSON file, hosted via Github Pages.
Meaning, the main purpose for the JSON is not for local testing, but for serving the context on the web.

2022-01-28 21:10 UTC, davidlehn commented
@dmitrizagidulin Ah yes, I forgot that use case.  Would be good to figure out how to write a github action that checks to make sure js and json are in sync.  As was seen here, that can be an issue and is difficult to spot.

2022-01-28 21:16 UTC, davidlehn commented
Added tracking issue: https://github.com/digitalbazaar/context-template/issues/6

2022-01-31 15:31 UTC, merged